### ISSUE TITLE
The from clause is missing table name when its assumed as a keyword

### ISSUE THREAD

**Issue by scottgblood** [bruce-dunwiddie/tsql-parser#22]
Hi,

I have a table in my database called Case (its a case management database), however the database platform does not support the case statement (hence the name being used).

When parsing a simple query on this table , i.e. SELECT Id, LastModifiedDate FROM Case the TSQLSelectStatement.From.Tokens is missing the table name because it is implied that the from statement contains another keyword.

**Comment by bruce-dunwiddie** [comment]
Unfortunately, parsing rules for these situations and even lower level things like quotes vs ticks to escape table names become very specific to certain database vendors and this library is currently specific to Microsoft's flavor of SQL called TSQL.

It's very surprising that the database platform that you're working with does not have CASE as a reserved word because it appears to even be a reserved word in ANSI SQL, http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc36271.1550/html/blocks/BEIJHIFE.htm , which is the more global standard that almost all vendors support near 100%.

You're going to have to find a parser that supports your database platform's specific flavor of SQL, or attempt to hack around it using one that is close enough and coding for all of the edge cases.

**Comment by omelhus** [comment]
By wrapping case in [] (like [case]) it would be valid t-sql and should be accepted by the parser. Not sure if this library handles it though.

**Comment by bruce-dunwiddie** [comment]
@omelhus yes, the parser will pick up on either square brackets or quoted identifiers, depending on the options set, and return it as an identifier instead of a keyword, so if changing the sql text is an option for @scottgblood , then yes, that should work for this particular instance.

**Comment by scottgblood** [comment]
Hi both,

The square brackets were the answer, unfortunately the Salesforce provider hates square brackets too but a simple check when using the parser means I can remove them too, should of really thought about that myself so apologies for wasting your time.

Ideally I would like to use a specific parser for SOSQL however also need to parse TSQL so this library pretty much does the trick for me.

Cheers
