### ISSUE TITLE
Negative numbers are not identified as single token

### ISSUE THREAD

**Issue by int0x81** [bruce-dunwiddie/tsql-parser#34]
In the following example:

`SELECT someColumn_01,
            someColumn_02 * -2 AS someAlias
FROM someTable`

the `-2` is **not** identified as single token of type `TSQLTokenType.NumericLiteral` but as two tokens `TSQLTokenType.Operator` and `TSQLTokenType.NumericLiteral`.

**Comment by bruce-dunwiddie** [comment]
I understand the annoyance, but this would be by design. From a tokenizing perspective, there's no way for the tokenizer to differentiate between those two situations. Only a higher level statement parser could look to see what token was preceding and know that this is a negative number. It would need to see if the preceding token was an operator, of a list of possible math operators. I think most parsers actually treat this situation as a subtraction, but then the evaluators inject a 0 to to get to a negative result, as opposed to making it a negative number to begin with.
