### ISSUE TITLE
Function Parse completes too early

### ISSUE THREAD

**Issue by dibbdob** [bruce-dunwiddie/tsql-parser#47]
Firstly, great library!!!

I do have one issue though. I have the following script that I wish to parse:

```
CREATE Function [dbo].[Test] ()
RETURNS INT
AS
BEGIN

Return 1;
END
GO

```

However, after parsing is the generated tokens do not include the last two lines.  This creates a problem for me as I wish to parse the tokens and add script (a DROP IF EXISTS before the function) and then run it - but the SQL Server is complaining when it comes to parse the result.

```
END
GO
```
The code I'm using is (version 1.2.7):

var parsedResults = TSQL.TSQLStatementReader.ParseStatements(script, true, true);

Are there other options I should pass when I'm parsing the sql?
Test file attached.

[Test.txt](https://github.com/bruce-dunwiddie/tsql-parser/files/3453040/Test.txt)

**Comment by bruce-dunwiddie** [comment]
I suggest you use TSQLTokenizer for what you're currently trying to accomplish instead of TSQLStatementReader. If you look at the second code example at https://github.com/bruce-dunwiddie/tsql-parser/wiki/TSQL-Parser-Code-Samples , there's code for using the tokenizer. I've also written a fiddle specific to your exact example just to verify, https://dotnetfiddle.net/YMTIjW .

**Comment by dibbdob** [comment]
Wow, that was quick! - I'll investigate your suggestion, thanks loads!

**Comment by dibbdob** [comment]
All works as you suggested.  Many thanks.
